#!/dis/sh script
load std

wmrun bind -a '#A' /dev # audio
wmrun bind -b /icons/tinytk /icons/tk

menu ''	''
menu Kbd			{ wm/keyboard }
menu Pen			{ wm/pen }
menu Halt		{ wmrun shutdown -h }

wmrun wm/sh -w 250 -h 90 -ic '
	fn rrtc { cat ''#r/rtc''; echo }
	fn rnes { cat /net/ether0/ifstats }
	fn wnec { echo -n $* > /net/ether0/0/ctl }

	cat /net/ether0/clone > /dev/null
	wnec scan 1
	sleep 1
	rnes

	wnec channel 11
	wnec essid 1
	rnes

	date
	auplay /usr/inferno/lib/invhit.iaf
	'

