<../../../../mkconfig
#<../../../../../mkconfig

TARG=\
	touchprint.dis\
	memfiddle.dis\
	rawimage.dis\
	imagerle.dis\
	morse.dis\

MODULES=\

SYSMODULES=\
	bufio.m\
	draw.m\
	devpointer.m\
	string.m\
	sys.m\
	tk.m\
	tkclient.m\
	wmclient.m\
	wmsrv.m\

DISBIN=$ROOT/dis/nds

<$ROOT/mkfiles/mkdis
