#!/dis/sh.dis
# mkkoch: a koch morse code generator
load std
load arg

#echo args $* >[1=2]

aflag=0
nchars=2
wpm=20
secs=60

args=$*
(arg
	a  {aflag=1}
	c+ {nchars=$arg}
	w+ {wpm=$arg}
	s+ {secs=$arg}
	'*' {echo unknown option $opt}
	- $args
)

fn kochtext{
	PARIS=(P A R I S)
	kochstr='kmrsuaptlowi.njef0yv,g5/q9zh38b?427c1d6x'
	kochlst=( `{echo $kochstr | sed 's/(.)/ \1/g' | tr a-z A-Z} )

	indexlst=`{
	{
	echo 'nwords= '$secs ' * ' $wpm ' / 60'
	echo 'for(w=0; w<nwords; w++){'
	echo '	wordlen=int('$#PARIS' - 3 + 3 * rand)'
	echo '	for(c=0; c<wordlen; c++){'
	echo '		i= 1 + int('$nchars' * rand)'
	echo '		print i, "\n"'
	echo '	}'
	echo '	print 0, "\n"'
	echo '}'
	} | calc}

	text=''
	for i in $indexlst{
		if {~ $i 0}{
			text=$text^' '
		}{
			text=$text^${index $i $kochlst}
		}
	}
	echo $text
}

if{~ $aflag 1}{
	file=koch-$nchars-$wpm-$secs
	kochtext > $file.txt
	cat $file.txt | morse -e | morse -w $wpm -aec > $file.raw
	cat $file.raw | raw2iaf -p -b -m -8 > $file.iaf
	iaf2wav < $file.iaf > $file.wav
	
	echo $file
}{
	kochtext
}
